### ISSUE TITLE
DC转QQ群无法正常使用求助

### ISSUE THREAD

**Issue by LeoWrDeom** [Autuamn/nonebot-plugin-dcqq-relay#1]
求助，DC发消息bot无任何响应，也不会转发消息到Q群，QQ群发消息机器人会报错
需要的功能只是把DC消息转发Q群该如何设置，不需要Q群消息转发DC
以下是我的.env.X设置与报错信息
![QQ_1722337089592](https://github.com/user-attachments/assets/e41644a4-2019-4da7-8321-48205f1951f6)
![QQ_1722337303106](https://github.com/user-attachments/assets/4d7df880-7ccc-4e1d-9fd2-51e38dad8497)

**Comment by Autuamn** [comment]
你的机器人所处的网络能连接到 Discord 吗
有没有挂代理

**Comment by Autuamn** [comment]
> 需要的功能只是把DC消息转发Q群该如何设置，不需要Q群消息转发DC

这没有相关的设置呢

不过实现起来也简单

对于你来说，只需要：
1. 进入这个目录：`G:\Lagrange.Core\Lagrangevenv\lib\site-packages\nonebot_plugin_dcqq_relay`
2. 编辑这个文件：`utils.py`

在 26-34 行处：
把
```python
async def check_messages(
    bot: Union[qq_Bot, dc_Bot],
    event: Union[
        GroupMessageEvent,
        MessageCreateEvent,
        GroupRecallNoticeEvent,
        MessageDeleteEvent,
    ],
) -> bool:
```
改成
```python
async def check_messages(
    bot: dc_Bot,
    event: Union[
        MessageCreateEvent,
        MessageDeleteEvent,
    ],
) -> bool:
```

让他不理会 QQ 的消息就行

对于这种改动行为会在插件更新后失效，所以就不要更新这个插件先

之后可能会出一个开关

**Comment by LeoWrDeom** [comment]
谢谢，我的网络可以连接到Discord，但是无论我在Discord发什么消息，他都不会转发

**Comment by Autuamn** [comment]
能否将日志等级调成DEBUG，并给一份刚启动时的日志。重要信息记得打码

**Comment by LeoWrDeom** [comment]
请问是我的设置哪里不对吗
![image](https://github.com/user-attachments/assets/ea344650-a6f1-44a5-86ae-42b793b42d89)
![image](https://github.com/user-attachments/assets/60715d80-1aa4-4cbb-afde-c9910152e9c2)
![image](https://github.com/user-attachments/assets/6113e9c7-badf-49bc-bd9d-5b56cf0ca2ae)

**Comment by Autuamn** [comment]
我没有看到类似 `08-07 17:58:55 [INFO] nonebot | Discord | Bot 1208320000000000000 connected` 的日志

请检查是否正确配置了 `discord` 适配器

**Comment by LeoWrDeom** [comment]
我确认已安装Discord适配器，但是却始终没有这样的提示

**Comment by Autuamn** [comment]
请检查配置文件，是否符合 [discord 适配器的文档](https://github.com/nonebot/adapter-discord?tab=readme-ov-file#%E9%85%8D%E7%BD%AE)要求

也就是说，请至少在配置文件中加入一下配置项：
```dotenv
DISCORD_BOTS='
[
  {
    "token": "xxx",
    "intent": {
      "guild_messages": true,
      "direct_messages": true,
      "message_content": true
    },
    "application_commands": {"*": ["*"]}
  }
]
'
```

推荐像 https://github.com/nonebot/adapter-discord/issues/21#issuecomment-2253729567 所说在 `intent` 添加 `"message_content": true`，以免收不到 `content`

**Comment by LeoWrDeom** [comment]
请问您要看的是这个吗
![QQ20240808-202218](https://github.com/user-attachments/assets/39ae980c-6019-4f6d-aa0e-54a08db167d3)

**Comment by Autuamn** [comment]
看来是你的 Discord 适配器没有正确加载，正确加载会有这样的日志

```
08-08 20:47:55 [DEBUG] nonebot | Succeeded to load adapter "Discord"
08-08 20:47:55 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
```

## 如果使用 nb 启动
安装一下就行

```bash
nb adapter install nonebot-adapter-discord
```
## 如果目录里有 `bot.py` 入口文件
在头部添加引入

```python
from nonebot.adapters.discord import Adapter as DISCORDAdapter
```
并在 `driver = nonebot.get_driver()` 后一行添加

```python
driver.register_adapter(DISCORDAdapter)
```
<details><summary>bot.py 示例</summary>
<p>

```python
import nonebot
from nonebot.adapters.discord import Adapter as DISCORDAdapter
from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter

nonebot.init()

driver = nonebot.get_driver()
driver.register_adapter(DISCORDAdapter)

driver.register_adapter(ONEBOT_V11Adapter)

nonebot.load_builtin_plugins('echo')


nonebot.load_from_toml("pyproject.toml")


if __name__ == "__main__":
    nonebot.run()
```

</p>
</details>

**Comment by LeoWrDeom** [comment]
已经按您说的配置，可是又出现了新问题
![image](https://github.com/user-attachments/assets/82230b34-e384-4cff-a109-09dcfc3ecdae)

**Comment by LeoWrDeom** [comment]
这是新的加载页
![image](https://github.com/user-attachments/assets/760b3308-4f48-408b-b068-8c54655c11ea)

**Comment by LeoWrDeom** [comment]
安装了开发版的discord适配器，没有了上述报错，又有新的报错，
![image](https://github.com/user-attachments/assets/751cab77-77ea-4561-8915-1ec20696f247)

**Comment by LeoWrDeom** [comment]
开发版的dcqq无法pip
![image](https://github.com/user-attachments/assets/ceb5f8ad-0b24-4494-9aba-e0c29e98b3d5)

**Comment by LeoWrDeom** [comment]
dc to qq 消息无法转发
![image](https://github.com/user-attachments/assets/baa92791-3d33-47bf-9788-f182363dd0ac)

**Comment by Autuamn** [comment]
请试试最新的开发版

readme中的安装命令是错的🫠，抱歉，已经更正了

```bash
pip install git+https://github.com/Autuamn/nonebot-plugin-dcqq-relay.git@main
```

**Comment by LeoWrDeom** [comment]
可以用了，谢谢您！

**Comment by shininome** [comment]
> > 需要的功能只是把DC消息转发Q群该如何设置，不需要Q群消息转发DC
> 
> 这没有相关的设置呢
> 
> 不过实现起来也简单
> 
> 对于你来说，只需要：
> 
> 1. 进入这个目录：`G:\Lagrange.Core\Lagrangevenv\lib\site-packages\nonebot_plugin_dcqq_relay`
> 2. 编辑这个文件：`utils.py`
> 
> 在 26-34 行处： 把
> 
> ```python
> async def check_messages(
>     bot: Union[qq_Bot, dc_Bot],
>     event: Union[
>         GroupMessageEvent,
>         MessageCreateEvent,
>         GroupRecallNoticeEvent,
>         MessageDeleteEvent,
>     ],
> ) -> bool:
> ```
> 
> 改成
> 
> ```python
> async def check_messages(
>     bot: dc_Bot,
>     event: Union[
>         MessageCreateEvent,
>         MessageDeleteEvent,
>     ],
> ) -> bool:
> ```
> 
> 让他不理会 QQ 的消息就行
> 
> 对于这种改动行为会在插件更新后失效，所以就不要更新这个插件先
> 
> 之后可能会出一个开关

请问有开关了吗~

**Comment by Autuamn** [comment]
> 请问有开关了吗~

还没
